%PlotAudiogram.m
hold off;
     Sel = [1:length(handles.freq)];
     plot(Sel, handles.HearThres(1,Sel), 'x-b');
hold on;
set(handles.Audiogram,                            ...
    'XScale', 'lin',                              ...
    'Xlim',   [0, length(handles.freq)+1],        ... 
    'XTick',  [1:length(handles.freq)],           ... 
    'XTickLabel', handles.freq*1e-3,              ...
    'Ylim',   [-30,                               ...
               120],                              ...
    'FontUnits',   'pixels',                      ...
    'FontSize', 10.667,                           ...
    'FontWeight', 'normal'                        ...
   );
line([7.5, 7.5], [-30,120], 'color', 'k');

plot(Sel, handles.HearThres(2,Sel), 'o-r');
xlabel('frequency [kHz]');
ylabel('hearing threshold [dB HL]');