%SetPlayer.m
% load the audioplayer with the signal and
% sets the attenuators to the level desired for playing
attn = handles.AttnLevel; 
% bpoint = -90;
%                     
% if attn < bpoint,                              % maximal slider attenuation
%   SndcrdLevel(bpoint.*[1,1], handles.MixerID2);% set maximum slider
%   handles.SndPlay =                     ...    % create soundplayer object
%     audioplayer(                        ...
%      MakeStereo(dB2amp(handles.S.wave,  ...    % signal at desired level
%                        + handles.S.norm ...    % to <-1..1> range
%                        + attn           ...    % plus extra attenuation
%                        - bpoint),       ...    
%                 handles.S.sil,          ...
%                 ~get(handles.LeftEar,   ...
%                     'value')),          ...
%      handles.S.fs,                      ...
%      16,                                ... 
%      handles.MixerID1);      
% else
%  SndcrdLevel([attn,attn], handles.MixerID2);   % set slider
%  handles.SndPlay =                      ...    % create soundplayer object               
%    audioplayer(                         ...
%     MakeStereo(dB2amp(handles.S.wave,   ...  
%                       + handles.S.norm),...
%                 handles.S.sil,          ...
%                 ~get(handles.LeftEar,   ...
%                     'value')),          ...
%                handles.S.fs,            ...
% 	             16,                      ... 
%   			       handles.MixerID1);      
% end;