%UpdateVolumeSlider
set(handles.LevelText,               ... % display current level
    'String',                        ...
    sprintf('%-3.0f dB',CurrentLevel));
handles.HearThres(get(handles.RightEar, ...
                      'value')          ...
                  + 1,                  ...
                  handles.CurFreqItem   ...
                 )                      ...
        = CurrentLevel;

PlotAudiogram;

handles.AttnLevel  = handles.S.norm + CurrentLevel;
handles.AttnChange = 1;                  % slider was changed