%ShowThres.m
%display hearing thresholds in corresponding boxes
ThresAll = [handles.ThrLef012, handles.ThrRig012; ... 
            handles.ThrLef025, handles.ThrRig025; ... 
            handles.ThrLef050, handles.ThrRig050; ... 
            handles.ThrLef100, handles.ThrRig100; ... 
            handles.ThrLef200, handles.ThrRig200; ... 
            handles.ThrLef400, handles.ThrRig400; ... 
            handles.ThrLef800, handles.ThrRig800];
for i = [1:7],
  for j = [1:2],
    set(ThresAll(i,j),                             ...
       'String',                                   ...
       sprintf('%2.0f', handles.SubjectThres(j,i)) ...
       ); 
  end
end